version: '3.1'
services:

  eureka-server:
    image: eureka-server 
    container_name: eureka-server
    build: 
      context: ./Eureka
      dockerfile: Dockerfile
    hostname: eureka-server
    ports:
      - "8761:8761"
    # networks:
    #         static-network:
    #           ipv4_address: 172.20.0.2
  
  dbpostgresql:
    image: postgres 
    environment: 
      POSTGRES_USER: postgres 
      POSTGRES_PASSWORD: postgres
    ports: 
      - "1389:5432"
    restart: unless-stopped
    depends_on: 
      - eureka-server
    links:
      - "eureka-server:eureka-server"
    # networks:
    #         - static-network

  bank-service:
    image: bank-service
    container_name: bank-service
    build:
      context: ./bank-service
      dockerfile: Dockerfile 
    environment: 
      REGISTRY_HOST: eureka-server 
      REGISTRY_PORT: 8761
      POSTGRES_HOST: dbpostgresql
    ports: 
      - "8081:8081"
    depends_on: 
      - eureka-server
      - dbpostgresql
    links:
      - "eureka-server:eureka-server"
      - "dbpostgresql:dbpostgresql"
    # networks: 
    #   - static-network

  paypal-service:
    image: paypal-service
    container_name: paypal-service
    build:
      context: ./paypal-service
      dockerfile: Dockerfile
    environment:
      REGISTRY_HOST: eureka-server
      REGISTRY_PORT: 8761
      POSTGRES_HOST: dbpostgresql
    ports:
      - "8082:8082"
    depends_on:
      - eureka-server
      - dbpostgresql
    links:
      - "eureka-server:eureka-server"
      - "dbpostgresql:dbpostgresql"
    # networks:
    #   - static-network

  bitcoin-service:
    image: bitcoin-service
    container_name: bitcoin-service
    build:
      context: ./bitcoin-service
      dockerfile: Dockerfile
    environment:
      REGISTRY_HOST: eureka-server
      REGISTRY_PORT: 8761
      POSTGRES_HOST: dbpostgresql
    ports:
      - "8083:8083"
    depends_on:
      - eureka-server
      - dbpostgresql
    links:
      - "eureka-server:eureka-server"
      - "dbpostgresql:dbpostgresql"
    # networks:
    #   - static-network

  zuul:
    image: zuul
    container_name: zuul
    build: 
      context: ./Zuul
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on: 
      - eureka-server
    environment: 
      REGISTRY_HOST: eureka-server
      REGISTRY_PORT: 8761
      # SPRING_CLOUD_GATEWAY_ROUTES[0]_ID: payment-service
      # SPRING_CLOUD_GATEWAY_ROUTES[0]_URI: http://payment-service:8081
    links:
      - "eureka-server:eureka-server"
    # networks:
    #     - static-network

# networks:
#     static-network:
#         ipam:
#             config:
#                 - subnet: 172.20.0.0/16
    # networks:
    #   static-network:

  # app:
  #   container_name: payment-service
  #   image: payment-service
  #   build:
  #     context: ./payment-service
  #   depends_on:
  #     - dbpostgresql
  #   environment:
  #     DB_PATH: jdbc:postgresql://dbpostgresql:5432/
  #   networks: 
  #     - static-network


  # dbpostgresql:
  #   image: postgres
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     - POSTGRES_PASSWORD=password
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_DB=mydb
  #   networks: 
  #     - static-network
# networks: 
#     static-network: