zuul:
  prefix: /api
  routes:
    pcc-service:
      path: /pcc/**
      serviceId: pcc
    raiffeisen-service:
      path: /raiffeisen/**
      serviceId: raiffeisen
    unicredit-service:
      path: /unicredit/**
      serviceId: unicredit
    bitcoin-service:
      path: /bitcoin/**
      serviceId: bitcoin
    paypal-service:
      path: /paypal/**
      serviceId: paypal
