zuul:
  prefix: /api
  routes:
    pcc-service:
      path: /pcc/**
      serviceId: pcc
    raiffeisen-service:
      path: /raiffeisen/**
      serviceId: raiffeisen
    unicredit-service:
      path: /unicredit/**
      serviceId: unicredit
    bitcoin-service:
      path: /bitcoin/**
      serviceId: bitcoin
    paypal-service:
      path: /paypal/**
      serviceId: paypal
server:
  ssl:
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: tomcat
    key-password: password
  port: 8443